/**
 * @file events.h
 * @brief Event system definitions for UI components
 * 
 * This file defines event types used for communication between
 * UI components and the main application state.
 */

#pragma once

/**
 * @brief Event types for settings panel interactions
 * 
 * Defines the types of events that can be generated by the settings
 * panel and other UI components.
 */
enum class SettingsEventType { 
    None  ///< No event or placeholder value
};
